### ISSUE TITLE
Question about terminal raw mode

### ISSUE THREAD

**Issue by technomancy** [dlannan/ljos#1]
Hello! I'm very interested in the idea of an OS that's all running inside LuaJIT; this project is very cool to me.

The first thing I did on it is load up a repl for [Fennel](https://fennel-lang.org), the programming language I work on that runs in LuaJIT. It worked perfectly.

Next I tried to get [Polywell](https://git.sr.ht/~technomancy/polywell/), my text editor written in Fennel, to run in ljos. This was more difficult as it was originally designed to run in Love2d, but I was able to port it to work inside a terminal in Linux. However, it doesn't work in ljos because I can't find a way to set the terminal to raw mode. In Linux this is done with the following snippet: `os.execute("stty raw -echo 2> /dev/null")` which unsurprisingly seems to have no effect in ljos.

How does one set the terminal to raw mode in ljos? (and back again when finished)

I found one mention of an stty syscall in https://github.com/dlannan/ljos/blob/master/barebones/lua/lua/libs/syscall/linux/x86/nr.lua#L36 but I don't know enough about C or the FFI to see how to invoke it without some hints.

Thanks!

**Comment by dlannan** [comment]
Hi. Thanks for getting it running - I hope I dont break it too much as I add new features :) 
Yes. I think the main problem there is because the command is using the stdin/out reduirection ">" which is not within the console command set (not sure how to implement that yet). 
The main thing to understand about the console, is that it is not a tty. Its a luajit instance with a custom commandline handler. So "raw mode" as such, kind of doesnt exist ;) I know this is probably not a big help :) 
What I can do, is add an stty command that will give you a similar operation - the command you have above redirects stdout to null. This is quite easy to do in other ways as well. For example, you can halt the console loop when the application launches, then everything should be fine, and just re-enable the loop when you return. 
[edit] May need to disable stdout too. Fairly easy todo from lua so that might help too.

Add a command to run your own editor somewhere here (see kilo for launching an editor):
https://github.com/dlannan/ljos/tree/master/barebones/lua/lua/deps/commands

Add a lua file, and you might need to use a dofile styled call rather than exec. I can make a sample for you - is your editor a lua script or a binary?

Create a global variable in boot.lua or in console.lua below. Something like: _G.app_running = false
https://github.com/dlannan/ljos/blob/7f2c26e4f70f674094cb04e944cf95b9bd362bb4/barebones/lua/lua/deps/console.lua#L265
Change this while to include: ```if _G.app_running == false then <do everything in loop> end```
This will mean the 'console' will be dead when launching an app. In your command simply add
```_G.app_running = true  << run editor commands >> _G.app_running = false ```

That should work. 
I need to do something like this for my graphical apps (binaries) anyway, so if you want I can probably get something in over the next few days.

Im currently working on a complete graphical UI / rendering setup at the moment so some things may be a bit unstable. I'll start branching soon since the basics are sort of working (although cursors, history and tab completion are on my list of todos.)
Hope this helps. Let me know if youd like something put in.

**Comment by technomancy** [comment]
> I think the main problem there is because the command is using the stdin/out reduirection ">" which is not within the console command set (not sure how to implement that yet).

No, the redirection is not really relevant; I expect the problem is that the `stty` executable doesn't exist at all in ljos because it's part of GNU Coreutils.

> The main thing to understand about the console, is that it is not a tty. Its a luajit instance with a custom commandline handler. So "raw mode" as such, kind of doesnt exist

I don't think this is true; raw mode is definitely present since it's activated when using kilo.

> Create a global variable in boot.lua or in console.lua below. Something like: _G.app_running = false

This is definitely not necessary when running the Fennel repl. I can simply run `dofile fennel` as a command and it's fine. Is there something different about my editor that would make a more complicated approach necessary? It seems I should just be able to `dofile` it, as the editor has been compiled to a single standalone lua file.

I did a little digging thru the tests for ljsyscall and I got it working on Debian without shelling out to `stty` by calling functions from the `syscall` library. I see that `syscall` is included in ljos; however it does not seem to be packaged in a way that works. Attempting to load `syscall` gives `module 'syscall.abi' not found` which makes me think that it's not set up in a way that allows it to be loaded from a subdirectory.

I'll see if I can tweak it a bit to use relative requires and see if that fixes things. Is there any other code already using the `syscall` library, and if so is there a special trick to loading it beyond just `require`?

**Comment by technomancy** [comment]
I found out what the problem was--it's because the `dofile` command is not actually `dofile`; it's launching a completely independent LuaJIT process which has not had its `package.path` configured as needed. Once I copied the `package.path` tweaks from `boot.lua` into my own program, it started working fine. The following code sets raw mode for the terminal:

```
(fn luajit-raw-term []
  (let [syscall (require :syscall)
        termios (assert (syscall.tcgetattr 1))]
    (termios:makeraw)
    (assert (syscall.tcsetattr 1 "NOW" termios))))
```

![polywell](https://user-images.githubusercontent.com/141/100002816-edde6580-2d79-11eb-97b5-2f6e4a835576.png)

I think the behavior of `dofile` is really misleading; it would be better if the `dofile` command actually worked like `dofile`. The current functionality should be renamed so it reflects what it actually does; that command should probably be called `lua` or `luajit` to indicate that it creates what is essentially a subprocess.

**Comment by dlannan** [comment]
Ahh. ok. Thats all making sense. And yes, fair comment - dofile is a little misleading. It was originally the normal dofile, but this is kind of dangerous doing that because then everything is running in the master luajit process (which is not how things are going to happen :) ). The master luajit process will become like a general process manager and system init. Theres alot more to come. 
There is a luajit in sbin, that can be run as well. If you use exec sbin/luajit. 
The system is not what Id call "ready for full use" at the moment, so please excuse some of these nuances. 
Glad you got it working - looks great!
I'll add some bugs, so I dont forget to fix some of these things up. Thanks again.

**Comment by dlannan** [comment]
Oh. On some of the other notes. 
Rawmode is not really rawmode. Because the kernel only loads a 'shim' of a terminal. And then the dev is only setup using tempfs so this means proper tty and such (which is usually done by udev and tools like busybox) are not really complete features and wont behave as such. Kilo works because it only handles stdin/out which is mapped early in boot.lua. Its why the redirect doesnt work, there is no redirect because there is no shell running and so os execute can really only run things directly. In fact many things wont work at all because some of the simple piping, dev mapping and redirection is not there.
I hope to get some of this working, but I dont really want to implement a large portion of it because its not intended to replicate linux gnu tools (btw, there are no gnu tools either - although I have tested ifconfig and that seems to work happily ). 

Syscall is all because of the dofile and launching of the process (as you correctly found). I intend to launch luajit with an environment so that the package paths are already set when started. A number of other things to get sorted though. I'll try to get that in soon though. 

Also be aware this is an "in memory" file system too. which has no installation at the moment. That is going to be quite different as well (under the hood) so be careful if you are working on files and expecting them to be saved and persisted.

**Comment by dlannan** [comment]
I'll also start on the wiki too. To try and capture some of what is happening, why and how to work around it.

**Comment by dlannan** [comment]
Sorry about all these responding comments. Just want to clarify some things.
The _G.app_running will end up going in at some-stage in some form (might even remove the loop and use sigs or events). The main reason is that, like a tty, it needs to disable its parent process execution while the foreground child is running. You can see this when you run opt/flags (btw dont do this if you dont want to have to reboot :) ). The flags program runs graphics in the child process while the parent process is still executing the command line input loop. This is a bug and not intended design. 
The signal handlers I have are not processing the Ctrl+C signals either (I think luajit is overriding them) so this needs fixing as well. Lots to do...

**Comment by technomancy** [comment]
> The system is not what Id call "ready for full use" at the moment, so please excuse some of these nuances.

That's totally understood; I don't think there's any implication
otherwise. =) But it also makes it an exciting point to work with the
project because there are so many possibilities; nothing has been nailed
down yet. And the idea of an operating system where you have the
opportunity to read and understand *all* the code (ignoring the kernel
for a minute) is really appealing too.

> Rawmode is not really rawmode. Because the kernel only loads a 'shim' of a terminal.

I don't understand this part. Isn't the terminal provided by Linux the
exact same thing that I get when I hit ctrl-alt-f1 on my Debian laptop?
That seems like a "real" terminal; (or as real as a terminal can get
without being implemented in hardware like a vt100) the only relevant
limitation I know is that it supports only 8 colors and has to use 8-bit
representation of keycodes. (no way to distinguish between ctrl-i and
tab, for example.)  Is there more to it that I'm missing, or is that
accurate?

I don't care about shell redirection at all really. I need a terminal,
but to be honest I'm not even sure for my own personal use I want a
shell at all, even if it's something like lummander. I'm more interested
in building out an OS like a lisp machine where the editor is at the
heart of it and rather than having separate shell windows, everything is
done inside editor buffers. I've used this approach to build out games
in Love2d (https://technomancy.itch.io/bussard and
https://technomancy.itch.io/tremendous-quest-iv in particular) that
simulate operating systems inside the game, and it has worked really well.

(Not that ljos shouldn't have a more conventional-looking shell; it's
just not something I personally want to use.)

> I intend to launch luajit with an environment so that the package paths are already set when started.

Yes, this would help a lot! =)

I think the most helpful thing right now would be to describe the code
organization so you can see where stuff belongs. But maybe it would make
sense to reorganize first before documenting things the way they
are. For instance, what's the purpose of the "barebones" directory
rather than keeping that in the repo root? And it's rather confusing to
have a "lua" directory that contains another "lua" directory inside
it. And there are things inside the "deps" folder that are part of ljos
itself rather than being external dependencies. But then that folder
also has "ple" which is an external library. But why isn't that in "libs"?

**Comment by dlannan** [comment]
All very valid points. I'll run through the answers.
Code: Yes. There isnt alot to this. Which is why I like it alot too. I have been working with luajit since its early days, and Lua since 2002. So I do love the idea of having a clean, simple system driving everything. And thats one of the primary motivations for me. 

Editor: I see no problem running from an editor. It reminds me alot of Forth. Which I did love running as is. No mucking around. We can even make it a start param of the boot process, so you can fall back into a default editor env - ideal for dev.

Rawmode/Terminal: Yes. The terminal isnt really a terminal :) The normal ttys you describe have a _large_ amount of other features that we do not have. The default kernel term is extremely thin. Its use is intended for simply booting to a busybox or similar. So using it is likely to cause problems if you need common terminal features. 

Terminal Dev: Im not really sure how far to go with the terminal, but I will start writing up notes to try to figure out some targets. I too, dont really want a "huge" terminal system. Some basic features will be good, but not much more I think.

Code org: I agree entirely. I have a _lot_ of projects and notes on paper, and many previous systems I want to lift portions from to help with development, but I do need to get that into an architectural layout as well as define the structural layout of the file hierarchy too. 

The barebones folder, is basically indicating that its a "simplistic" starting point. I hope to migrate to  something bigger later. It also keeps the build space for the whole system separate from packages etc. Will change the name though, its a little less barebones now :) .. the lua in the lua folder, haha. This is kind of funny. During creation I realised I needed a folder for all the lua scripts (they were initially going in the root directory!!)/ Will rename the parent one to something more meaningful. 

Work for me has become a little busy at the moment. I hope to have a few weeks off over xmas, and some time in the coming weeks to get some of these items done. This week I was going to get OpenGLES into the system, but thats probably not going to happen now that I know there is a _vast_ amount of pain in doing that and getting it operational - its going to take a back seat, and we will have SDL1.2 for graphics instead (software with some hw accel on the framebuffer). 

Will try to get some notes up over the weekend. Thanks again for the interest.

Notes: Some folders and files are in weird places because they are either redundant, or in flux. Beware using initfs folder for anything, this is generated everytime a new build is done. Some shared libs wont be going into libs folder because libs is going to be explicitly system libs. Shared/custom/application libs will most likely reside _with_ the application. This is more about future execution than file org. Hope that helps a little.

**Comment by technomancy** [comment]
> Rawmode/Terminal: Yes. The terminal isnt really a terminal :) The normal ttys you describe have a _large_ amount of other features that we do not have. The default kernel term is extremely thin. Its use is intended for simply booting to a busybox or similar. So using it is likely to cause problems if you need common terminal features.

I think I understand this; but just to be extra clear: is it accurate
that the terminal I get with ljos is the same as the terminal I get on
Debian if I press ctrl-alt-f1? I can live with those limitations, but if
there are additional limitations I would like to be aware of them.

**Comment by dlannan-fmad** [comment]
No the terminal is not like Ctrl+F1 -> F4 These are ttys running a shell - bash or whatever the system decides to use (like csh or others). There is no shell (busybox or syslinux is _not_ loaded, so these are not initialised). So what you have is a _pure_ kernel console, which can do _some_ terminal things, and we can run any syscalls (Into kernel) but anything that needs bash, or /dev tty related features will probably not function correctly. HOWEVER :) .. some of the parts of terminals, are implemented in the default kernel console. I'll try to dig up the main differences, but its mostly things like redirecting, piping, and signal control (im sure theres more too).

**Comment by technomancy** [comment]
Thanks, I understand that it does not have any shell features; I was specifically asking about the terminal features rather than the shell features. Sounds like it's the same from a terminal perspective so that takes care of my question here. =)

**Comment by dlannan** [comment]
Sorry, No, the terminal is _not_ the same as other linux terminals. There is no init that creates process and signal handling for them, and many other features. So ljos terminal is _not_ the same as Ctrl+F1->F4 and you will find differences. 
Note: Its not just the terminal when you use Ctrl+F1 - its the whole linux user_mode interface. Theres is _no_ user_mode interface in ljos.

**Comment by technomancy** [comment]
> Sorry, No, the terminal is _not_ the same as other linux terminals. There is no init that creates process and signal handling for them, and many other features.

But that has nothing to do with the terminal; that has to do with the things that run inside the terminal, like shells.

**Comment by dlannan-fmad** [comment]
I think we might have our wires crossed. The terminal interface in most linux installations is _not_ the linux kernel default terminal (or console). We _are_ using the default kernel terminal (thats built-in to the kernel running in kernel mode). The system starts by launching the "init" process for the whole linux system. On normal linux variants, the init process launches the terminals you are referring to - Ctrl+F1->F4 (and management for them). The default kernel terminal is _not_ accessible in a normal linux (you can hack it to get to it, but its not recommended). Mainly because it runs in kernel mode which makes it very dangerous to use with all the linux tools available. 

For ljos, the "terminal" equivalent for a Ctrl+F1 type terminal is the lummander based console. Which is very different. 

The init process for the ljos kernel only creates a process that handles some sigs, and then launches the master luajit process - there is no "running" kernel terminal for ljos. There is a built-in terminal _system_ in the kernel (as mentioned previously) but this is _very_ rudimentary, and hence why you shouldnt expect it to work similar to normal linux, its just not the same. 

From the perspective of an application, the default kernel terminal doesnt exist in ljos. What does exist, are terminal features like stdio, some of the devs (/dev/console, dev/tty etc), some of the signal handling (Ctrl+C should work but currently broken) and a number of config elements. When an application runs and it uses clib (or other libs) to access terminal type features, it is very likely there will be missing components. If you are accessing syscall kernel library elements many features will be available (if it was built into the kernel). 

Maybe a better way to do this would be a diagram. 
![image](https://user-images.githubusercontent.com/60128766/100529547-a869de80-3238-11eb-874a-d997d4340ff7.png)

This is not an exhaustive look at the startup process, just a simple overview. So you see the "terminals" are very different in execution, and features. Hence, why I would be very wary of relying on a complete set of features. Simple set, should be fine.
